In [3]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21])

In [6]:
a.cumsum(axis=0)

array([[1, 2, 3],
       [5, 7, 9]])

In [7]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [8]:
arr2.cumprod()

array([  1,   2,   6,  24, 120])

In [10]:
arr3 = np.array([[0,1,2], [3,4,5], [6,7,8]])
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
arr3.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
arr4 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr4.cumprod()

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [20]:
arr4.cumprod(axis=1)

array([[  1,   2,   6],
       [  4,  20, 120],
       [  7,  56, 504]])

In [21]:
arr4.cumprod(axis=0)

array([[  1,   2,   3],
       [  4,  10,  18],
       [ 28,  80, 162]])